// get all persons
GET http://localhost:3001/api/persons

###

// Prod 

GET https://blooming-sea-12590.herokuapp.com/api/persons

###

// get single person 

GET http://localhost:3001/api/persons/6075aebcba93b14980160644

###

// Prod 

GET https://blooming-sea-12590.herokuapp.com/api/persons/76785301

####

// delete person 

DELETE http://localhost:3001/api/persons/11755650

###

// Prod 

DELETE https://blooming-sea-12590.herokuapp.com/api/11755650

###

// create new person

POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jacinto",
  "number": "23452346"
}

###

// Prod

POST  https://blooming-sea-12590.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Periquito",
  "number": "23452346"
}