// get all blogs
GET http://localHost:3003/api/blogs

###

// post new blog

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###

// Delete Post

DELETE http://localhost:3003/api/blogs/61a0875aa5895b309d8e3bc4